sudo: required
before_install:
  - sudo apt-get update && sudo apt-get install g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev libboost1.63-dev git-core build-essential cmake libpcsclite-dev miniupnpc libunbound-dev graphviz pkg-config libssl-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make
